In [7]:
import praw
import time
import requests
import os
from urllib.parse import urlparse
from concurrent.futures import ThreadPoolExecutor
from typing import List
from tqdm import tqdm

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
from PIL import Image
import random
import glob

# Create PDF with multiple pages
from matplotlib.backends.backend_pdf import PdfPages

In [18]:
roster_path = '../data/FA25 CY3 Residents Roster copy.xlsx'
imgs_path = '../data/cat_memes/'

In [ ]:
reddit = praw.Reddit(
    client_id='ShnBSk3RTJklCQQsOVX0iw',      # Replace with your client ID
    client_secret='kHuwyBg6kotj-dsqLqu0eHiKCXVt-w',    # Replace with your client secret
    user_agent='cat_meme_bot',        # Replace with your descriptive user agent
    read_only=True  # Run in read-only mode
)

def download_image(post) -> bool:
    if not post.url.endswith(('.jpg', '.jpeg', '.png', '.gif')):
        return False
        
    filename = os.path.basename(urlparse(post.url).path)
    filepath = os.path.join(imgs_path, filename)
    
    try:
        response = requests.get(post.url)
        if response.status_code == 200:
            with open(filepath, 'wb') as f:
                f.write(response.content)
            return True
        else:
            print(f"Failed to download {post.url}")
            return False
    except Exception as e:
        print(f"Error downloading {post.url}: {str(e)}")
        return False

# Create imgs directory if it doesn't exist
os.makedirs(imgs_path, exist_ok=True)

# Get posts from subreddit
subreddit = reddit.subreddit('CatMemes')
posts = list(subreddit.hot(limit=200))

# Download images using thread pool with progress bar
with ThreadPoolExecutor(max_workers=10) as executor:
    results = list(tqdm(
        executor.map(download_image, posts),
        total=len(posts),
        desc="Downloading images"
    ))

print(f"Successfully downloaded {sum(results)} images")

In [20]:
# Read the Excel file
roster_df = pd.read_excel(roster_path)

roster_df

    DKUID Bed Space  Family Name   Given Name Gender  Move In  Check In
0     NaN    E-1101          NaN      Belinda      M      NaN       NaN
1     NaN    E-2123          NaN        Soham      M      NaN       NaN
2     NaN    E-2029          NaN        Shang      M      NaN       NaN
3     NaN    E-5125          NaN         Biki      M      NaN       NaN
4     NaN    E-3123          NaN       Audrey      M      NaN       NaN
5     NaN       NaN          NaN         Noza      M      NaN       NaN
6     NaN    E-2116          NaN         Coco      M      NaN       NaN
7     NaN    E-3029          NaN   Emberleigh      M      NaN       NaN
8     NaN        E-          NaN        Penny      M      NaN       NaN
9     NaN        F-          NaN         Coco      M      NaN       NaN
10    NaN         F          NaN       Feifei      M      NaN       NaN
11    NaN    E-4123          NaN         Leah      M      NaN       NaN
12    NaN    E-2127          NaN       Matyas      M      NaN       NaN
13    NaN    F-3032          NaN  Mohamed Ali      M      NaN       NaN
14    NaN    F-2032          NaN         Demi      M      NaN       NaN

In [21]:
# Filter residents
myHall_df = roster_df[
    # (roster_df['Bed Space'].str.startswith('F')) & 
    (roster_df['Gender'].str.startswith('M'))
]
myHall_df

    DKUID Bed Space  Family Name   Given Name Gender  Move In  Check In
0     NaN    E-1101          NaN      Belinda      M      NaN       NaN
1     NaN    E-2123          NaN        Soham      M      NaN       NaN
2     NaN    E-2029          NaN        Shang      M      NaN       NaN
3     NaN    E-5125          NaN         Biki      M      NaN       NaN
4     NaN    E-3123          NaN       Audrey      M      NaN       NaN
5     NaN       NaN          NaN         Noza      M      NaN       NaN
6     NaN    E-2116          NaN         Coco      M      NaN       NaN
7     NaN    E-3029          NaN   Emberleigh      M      NaN       NaN
8     NaN        E-          NaN        Penny      M      NaN       NaN
9     NaN        F-          NaN         Coco      M      NaN       NaN
10    NaN         F          NaN       Feifei      M      NaN       NaN
11    NaN    E-4123          NaN         Leah      M      NaN       NaN
12    NaN    E-2127          NaN       Matyas      M      NaN       NaN
13    NaN    F-3032          NaN  Mohamed Ali      M      NaN       NaN
14    NaN    F-2032          NaN         Demi      M      NaN       NaN

In [22]:
myHall_df.shape[0]

15

In [26]:
# Get list of downloaded cat memes
cat_memes = glob.glob(f"{imgs_path}/*.jpg") + glob.glob(f"{imgs_path}/*.png") + glob.glob(f"{imgs_path}/*.jpeg")

# Number of residents 
n_residents = len(myHall_df)

# Create output directory
os.makedirs('../out', exist_ok=True)

# Randomly shuffle cat memes
random.shuffle(cat_memes)

# Ensure we have enough unique memes
if len(cat_memes) < n_residents:
    print(f"Warning: Only {len(cat_memes)} unique memes available for {n_residents} residents")
    print("Some residents will not receive a meme")
    n_residents = len(cat_memes)  # Limit to available unique memes

pdf_path = os.path.join('../out', f"FA25 CY3 copy.pdf")
with PdfPages(pdf_path) as pdf:
    # Use enumerate to track which meme to use, limited to available unique memes
    for idx, (_, resident) in enumerate(myHall_df.iterrows()):
        if idx >= len(cat_memes):
            break
            
        # Create figure with exact A4 dimensions
        fig = plt.figure(figsize=(8.27, 11.69), dpi=300)
        
        # Set margins for better layout
        left_margin = 0.15
        right_margin = 0.85
        
        # Create main content area for image
        main_ax = fig.add_axes([left_margin, 0.2, right_margin-left_margin, 0.6])
        
        # Use indexed cat meme
        img = Image.open(cat_memes[idx])
        img_array = np.asarray(img)
        main_ax.imshow(img_array, aspect='auto')
        main_ax.axis('off')
        
        # Add decorative frame with double border
        for spine in main_ax.spines.values():
            spine.set_visible(True)
            spine.set_linewidth(3)
            spine.set_color('#1a237e')  # Deep blue
        
        # Add second decorative frame
        frame_ax = fig.add_axes([left_margin-0.02, 0.18, right_margin-left_margin+0.04, 0.64])
        frame_ax.axis('off')
        for spine in frame_ax.spines.values():
            spine.set_visible(True)
            spine.set_linewidth(1)
            spine.set_color('#5c6bc0')  # Lighter blue
            
        # Add resident info with enhanced styling
        name = resident['Given Name']
        bedspace = resident['Bed Space']
        
        # Title with name
        title_ax = fig.add_axes([left_margin, 0.85, right_margin-left_margin, 0.1])
        title_ax.axis('off')
        title_ax.text(0.5, 0.5, 
                     name,
                     ha='center',
                     va='center',
                     fontsize=40,
                     fontweight='bold',
                     fontfamily='DejaVu Sans',
                     color='#1a237e')
        
        # # Subtitle with bedspace
        # subtitle_ax = fig.add_axes([left_margin, 0.8, right_margin-left_margin, 0.05])
        # subtitle_ax.axis('off')
        # subtitle_ax.text(0.5, 0.5,
        #                 bedspace,
        #                 ha='center',
        #                 va='center',
        #                 fontsize=20,
        #                 fontfamily='DejaVu Sans',
        #                 color='#5c6bc0')
        
        # Add decorative header/footer lines
        for y_pos in [0.95, 0.05]:
            line_ax = fig.add_axes([0.1, y_pos, 0.8, 0.01])
            line_ax.axis('off')
            line_ax.axhline(y=0.5, color='#1a237e', linewidth=3)
            
        # Add subtle gradient background
        gradient = np.linspace(0, 1, 100).reshape(-1, 1)
        gradient = np.tile(gradient, (1, 2))
        bg_ax = fig.add_axes([0, 0, 1, 1], zorder=-1)
        bg_ax.imshow(gradient, cmap='Purples', alpha=0.1, aspect='auto')
        bg_ax.axis('off')
        
        # Save page
        pdf.savefig(fig, 
                   dpi=300,
                   bbox_inches='tight',
                   pad_inches=0.25)
        
        plt.close(fig)

In [ ]:
# Get list of downloaded cat memes
cat_memes = glob.glob(f"{imgs_path}/*.jpg") + glob.glob(f"{imgs_path}/*.png") + glob.glob(f"{imgs_path}/*.jpeg")

# Create output directory
os.makedirs('../out', exist_ok=True)

# Randomly shuffle cat memes
random.shuffle(cat_memes)

pdf_path = os.path.join('../out', f"SP25 CY1 Bulletin Board.pdf")
with PdfPages(pdf_path) as pdf:
    # Use enumerate to track which meme to use, limited to available unique memes
    for idx, cat_meme in enumerate(cat_memes[:50]):
        # Create figure with exact A4 dimensions
        fig = plt.figure(figsize=(8.27, 11.69), dpi=300)
        
        # Create main content area for image
        main_ax = fig.add_axes([0.1, 0.1, 0.8, 0.8])
        
        # Display cat meme
        img = Image.open(cat_meme)
        img_array = np.asarray(img)
        main_ax.imshow(img_array, aspect='auto')
        main_ax.axis('off')
        
        # Save page
        pdf.savefig(fig, 
                   dpi=300,
                   bbox_inches='tight',
                   pad_inches=0.25)
        
        plt.close(fig)